<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Fundamentos de Linguagem Python - Do Básico a Aplicações de IA</font>
# <font color='blue'>Operações Vetoriais e Manipulação de Matrizes com NumPy</font>

## 1. O Que é e Quando Usar o NumPy?

Leia o manual em pdf no Capítulo 8 do Curso.

In [2]:
# Instalando o NumPy
%pip install -q numpy==2.3.2

Note: you may need to restart the kernel to use updated packages.


In [3]:
# Importando a biblioteca NumPy
import numpy as np

Vamos começar comparando a performance do NumPy com Python puro (uso padrão da Linguagem Python).

In [4]:
# Imports
import math
import time

In [11]:
# Criando uma lista (vetor) com NumPy de 10 milhões de itens
precos_np = np.random.rand(10_000_000)
type(precos_np)

numpy.ndarray

In [12]:
# Cria uma lista (estrutura de dados padrão em Python Puro)
precos_list = list(precos_np)
type(precos_list)

list

In [13]:
# Operação com NumPy
t0 = time.time()
desc = precos_np * 0.90
final = desc + 5
raiz = np.sqrt(precos_np)
print("NumPy:", time.time() - t0, "segundos")

NumPy: 0.11652565002441406 segundos


In [14]:
# Mesma operação com Python puro
t0 = time.time()
desc = [p * 0.90 for p in precos_list]
final = [p + 5 for p in desc]
raiz = [math.sqrt(p) for p in precos_list]
print("Python puro:", time.time() - t0, "segundos")

Python puro: 1.5021531581878662 segundos


Nota: Os tempos acima foram obtidos em um Notebook Apple MacBook Pro Processador Apple Silicon M4 com 128 GB de RAM e Disco SSD.

---

Para 10 milhões de valores, o NumPy normalmente é muito mais rápido. Mas para poucos valores, o uso de loops com Python puro pode sair na frente porque o overhead do NumPy pesa mais que o ganho para poucos registros.

✅ Resumindo:

- Poucos elementos → Loops Python podem ser mais rápidos (overhead do NumPy é maior).

- Muitos elementos → NumPy é muito mais rápido e escalável.

É pela sua velocidade, que NumPy é amplamente usado em projetos de Ciência de Dados, Machine Learning e IA.

## 2. O Objeto ndarray

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPUs.

![DSA](imagem1.png)

In [15]:
# Criando um array de 1 dimensão (vetor) a partir de uma lista Python
vetor = np.array([17, 21, 100, 34])
print("\nVetor (Array 1D):\n")
print(vetor)


Vetor (Array 1D):

[ 17  21 100  34]


In [16]:
# Verificando atributos 
print("Formato (shape) do vetor:", vetor.shape) 
print("Número de dimensões (ndim) do vetor:", vetor.ndim)
print("Número total de elementos (size) do vetor:", vetor.size)

Formato (shape) do vetor: (4,)
Número de dimensões (ndim) do vetor: 1
Número total de elementos (size) do vetor: 4


In [17]:
# Criando um array de 2 dimensões (matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriz (Array 2D):\n")
print(matriz)


Matriz (Array 2D):

[[1 2 3]
 [4 5 6]]


In [18]:
# Verificando atributos 
print("Formato (shape) da matriz:", matriz.shape)  # (linhas, colunas)
print("Número de dimensões (ndim) da matriz:", matriz.ndim)
print("Número total de elementos (size) da matriz:", matriz.size)

Formato (shape) da matriz: (2, 3)
Número de dimensões (ndim) da matriz: 2
Número total de elementos (size) da matriz: 6


In [19]:
# Criando um array 3D usando np.arange()
arr = np.arange(24).reshape(4, 3, 2)
print("\nArray (Array 3D):\n")
print(arr)


Array (Array 3D):

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [20]:
# Verificando atributos 
print("Formato (shape) do array:", arr.shape) 
print("Número de dimensões (ndim) do array:", arr.ndim)
print("Número total de elementos (size) do array:", arr.size)

Formato (shape) do array: (4, 3, 2)
Número de dimensões (ndim) do array: 3
Número total de elementos (size) do array: 24


Array 3D — Um array com três eixos, sendo: shape = (profundidade, linhas, colunas) ou (altura, largura, canais) em imagens. 

Tensor 3D — Em Machine Learning e computação numérica, um tensor de ordem 3 é, de fato, um array 3D.

In [21]:
# Array 4D com valores sequenciais de 0 a 119 organizado em 2x3x4x5 (2 blocos, 3 "planos", 4 linhas, 5 colunas)
tensor_4d = np.arange(120).reshape(2, 3, 4, 5)
print(tensor_4d)  

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [22]:
# Verificando atributos importantes do array
print("Formato (shape) do array:", tensor_4d.shape) 
print("Número de dimensões (ndim) do array:", tensor_4d.ndim)
print("Número total de elementos (size) do array:", tensor_4d.size)

Formato (shape) do array: (2, 3, 4, 5)
Número de dimensões (ndim) do array: 4
Número total de elementos (size) do array: 120


## 3. Tipos de Dados do NumPy
<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
Diferente das listas em Python, os arrays NumPy são homogêneos; todos os elementos devem ter o mesmo tipo de dado. Isso é fundamental para a performance.

In [5]:
# NumPy infere o tipo de dado automaticamente
arr_inteiros = np.array([1, 2, 3])
print("Tipo de dado (inteiros):", arr_inteiros.dtype)

Tipo de dado (inteiros): int64


In [6]:
# NumPy infere o tipo de dado automaticamente
arr_float = np.array([1.0, 2.0, 3.0])
print("Tipo de dado (inteiros):", arr_float.dtype)

Tipo de dado (inteiros): float64


In [7]:
# Mas podemos especificar o tipo de dado durante a criação
arr_float = np.array([1, 2, 3], dtype = np.float64)
print("Tipo de dado (float64):", arr_float.dtype)
print("Array float:", arr_float)

Tipo de dado (float64): float64
Array float: [1. 2. 3.]


In [8]:
# Conversão para int64
arr_int = arr_float.astype(np.int64)
print("Tipo convertido:", arr_int.dtype)
print("Array convertido:", arr_int)

Tipo convertido: int64
Array convertido: [1 2 3]


## 4. Indexação e Fatiamento
<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
Acessar e modificar subconjuntos de dados em arrays é simples e poderoso.

In [9]:
# Vamos criar uma matriz 4x4 com números de 0 a 15
dados = np.arange(16).reshape(4, 4)
print("\nMatriz Original:\n")
print(dados)


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
# Acessando um elemento específico: linha 1, coluna 2 (lembre-se que a indexação em Python começa em 0)

print("\nMatriz Original:\n")

print(dados)

elemento = dados[1, 2]

print(f"\nElemento na posição [1, 2]: {elemento}\n")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Elemento na posição [1, 2]: 6



In [11]:
# Fatiando para obter a primeira linha completa (sintaxe pelo índice da linha)

print("\nMatriz Original:\n")

print(dados)

primeira_linha = dados[0] 

print(f"\nPrimeira linha:\n{primeira_linha}\n")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Primeira linha:
[0 1 2 3]



In [12]:
# Fatiando para obter a primeira linha completa (sintaxe pelo índice da linha e da coluna)

print("\nMatriz Original:\n")

print(dados)

primeira_linha = dados[0, :]

print(f"\nPrimeira linha:\n{primeira_linha}\n")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Primeira linha:
[0 1 2 3]



In [13]:
# Fatiando para obter a segunda coluna completa

print("\nMatriz Original:\n")

print(dados)

segunda_coluna = dados[:, 1]

print(f"\nSegunda coluna:\n{segunda_coluna}\n")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Segunda coluna:
[ 1  5  9 13]



In [14]:
# Fatiando um bloco 2x2 do canto superior esquerdo

print("\nMatriz Original:\n")

print(dados)

bloco_superior_esquerdo = dados[:2, :2]

print(f"\nBloco 2x2 superior esquerdo:\n{bloco_superior_esquerdo}\n")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Bloco 2x2 superior esquerdo:
[[0 1]
 [4 5]]



In [15]:
# Indexação booleana: selecionando apenas os números maiores que 10

print("\nMatriz Original:\n")

print(dados)

maiores_que_10 = dados[dados > 10]

print(f"\nNúmeros maiores que 10:\n {maiores_que_10}")


Matriz Original:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Números maiores que 10:
 [11 12 13 14 15]


Dada a matriz 5x5 abaixo, vamos criar um novo array que contenha apenas as linhas de índice par e as colunas de índice ímpar.

In [16]:
# Cria a matriz
matriz = np.arange(25).reshape(5, 5)

In [17]:
# Usamos o passo no slicing (start:stop:step)
# Para as linhas: '::2' significa do início ao fim, pulando de 2 em 2 (0, 2, 4)
# Para as colunas: '1::2' significa do índice 1 ao fim, pulando de 2 em 2 (1, 3)

resultado = matriz[::2, 1::2]

print("Matriz Original:")
print(matriz)
print("\nLinhas Pares e Colunas Ímpares:")
print(resultado)

Matriz Original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Linhas Pares e Colunas Ímpares:
[[ 1  3]
 [11 13]
 [21 23]]


## 5. Operações Matemáticas Vetorizadas

A "vetorização" permite aplicar operações em arrays inteiros de uma vez, sem a necessidade de loops for, o que é extremamente rápido. O NumPy usa implementações em Linguagem C otimizadas e faz operações em bloco sobre arrays inteiros, evitando o loop Python elemento a elemento. Isso brilha quando temos muitos dados (milhares ou milhões de elementos).

In [18]:
# Simulando dados de preços de produtos
precos = np.array([19.99, 25.50, 8.90, 43.00])
print(f"\nPreços originais: {precos}\n")


Preços originais: [19.99 25.5   8.9  43.  ]



In [19]:
# Aplicando um desconto de 10% a todos os preços de uma vez
precos_com_desconto = precos * 0.90
print(f"\nPreços com 10% de desconto: {precos_com_desconto}\n")


Preços com 10% de desconto: [17.991 22.95   8.01  38.7  ]



In [20]:
# Mesmo resultado da célula anterior usando Python puro

# Lista original de preços
precos_pp = [19.99, 25.50, 8.90, 43.00]

# Aplicando desconto de 10% usando list comprehension
precos_com_desconto_pp = [preco * 0.90 for preco in precos_pp]

print(f"\nPreços com 10% de desconto: {precos_com_desconto_pp}\n")


Preços com 10% de desconto: [17.991, 22.95, 8.01, 38.7]



In [21]:
# Adicionando um valor fixo de frete
precos_finais = precos_com_desconto + 5.00
print(f"\nPreços finais com frete: {precos_finais}\n")


Preços finais com frete: [22.991 27.95  13.01  43.7  ]



In [22]:
# Usando funções universais (ufuncs) do NumPy
# Exemplo: calculando a raiz quadrada de cada elemento
raizes = np.sqrt(precos)
print(f"\nRaiz quadrada dos preços: {raizes}")


Raiz quadrada dos preços: [4.47101778 5.04975247 2.98328678 6.55743852]


## 6. Agregações Estatísticas

Calcular estatísticas descritivas de um conjunto de dados é uma tarefa comum e muito otimizada no NumPy.

In [23]:
# Simulando as notas de 3 alunos em 4 provas
notas = np.array([
    [8.5, 7.0, 9.2, 6.5],  # Aluno 1
    [5.5, 6.8, 7.5, 8.0],  # Aluno 2
    [9.5, 9.0, 8.8, 10.0]  # Aluno 3
])

In [24]:
print("\nMatriz de Notas:\n")
print(notas)


Matriz de Notas:

[[ 8.5  7.   9.2  6.5]
 [ 5.5  6.8  7.5  8. ]
 [ 9.5  9.   8.8 10. ]]


In [25]:
type(notas)

numpy.ndarray

In [26]:
# Agregações na matriz inteira
print(f"\nMédia geral da turma:    {notas.mean():.2f}")
print(f"Nota máxima da turma:    {notas.max()}")
print(f"Nota mínima da turma:    {notas.min()}")
print(f"Soma de todas as notas:  {notas.sum()}\n")


Média geral da turma:    8.03
Nota máxima da turma:    10.0
Nota mínima da turma:    5.5
Soma de todas as notas:  96.3



In [27]:
# Agregações por eixo (axis)
# Média de cada aluno (agregando nas colunas, axis = 1) arredondando para duas casas decimais
media_por_aluno = notas.mean(axis = 1).round(2)
print(f"\nMédia de cada aluno: {media_por_aluno}\n")


Média de cada aluno: [7.8  6.95 9.32]



In [28]:
# Média de cada prova (agregando nas linhas, axis = 0) arredondando para duas casas decimais
media_por_prova = notas.mean(axis = 0).round(2)
print(f"\nMédia de cada prova: {media_por_prova}")


Média de cada prova: [7.83 7.6  8.5  8.17]


## 7. Broadcasting e Operações Entre Arrays

No NumPy, broadcasting é o mecanismo que permite realizar operações aritméticas entre arrays de formas (shapes) diferentes, sem precisar copiar ou replicar manualmente os dados. 

Ele funciona expandindo automaticamente as dimensões de arrays menores para que fiquem compatíveis com os maiores, seguindo um conjunto de regras. Isso evita laços (loops) explícitos e melhora muito a eficiência. 

Por exemplo, se você soma uma matriz 3×3 com um vetor de 3 elementos, o NumPy “estica” o vetor para que cada linha da matriz receba a soma correspondente elemento a elemento, sem criar cópias extras na memória.

In [29]:
# Matriz 3x3
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [30]:
type(matriz)

numpy.ndarray

In [31]:
matriz.shape

(3, 3)

In [32]:
# Vetor 1D com 3 elementos
vetor = np.array([10, 20, 30])

In [33]:
type(vetor)

numpy.ndarray

In [34]:
vetor.shape

(3,)

**Queremos somar os valores do vetor aos valores de CADA linha da matriz.**

In [35]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(vetor)

[10 20 30]


In [37]:
# Broadcasting: o vetor é "expandido" para cada linha da matriz
resultado = matriz + vetor

In [38]:
print("\nMatriz original:\n", matriz)
print("\nVetor:\n", vetor)
print("\nResultado com broadcasting:\n", resultado)


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vetor:
 [10 20 30]

Resultado com broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [39]:
# Matriz com faturamento de 3 produtos em 4 meses
faturamento = np.array([
    [100, 110, 120, 130], # Produto A
    [200, 210, 220, 230], # Produto B
    [300, 310, 320, 330]  # Produto C
])

In [40]:
type(faturamento)

numpy.ndarray

In [41]:
# Shape
faturamento.shape

(3, 4)

In [42]:
# Vetor com um bônus (incentivo) para cada produto
bonus_por_produto = np.array([5, 10, 15])

In [43]:
type(bonus_por_produto)

numpy.ndarray

In [ ]:
# Shape
bonus_por_produto.shape

**Queremos adicionar um bônus a cada valor de faturamento, por linha. Ou seja, todos os itens da primeira linha devem receber o bônus de 5, por exemplo, e assim por diante.**

In [44]:
print("\nFaturamento:\n")
print(faturamento)


Faturamento:

[[100 110 120 130]
 [200 210 220 230]
 [300 310 320 330]]


In [45]:
print("\nBônus por Produto:\n")
print(bonus_por_produto)


Bônus por Produto:

[ 5 10 15]


In [ ]:
# Poderíamos usar a vetorização e fazer algo assim:

#faturamento_com_bonus = faturamento + bonus_por_produto

Mas, por que a mensagem de erro? A própria mensagem já explica o que está ocorrendo.

In [46]:
# O NumPy "estica" (broadcast) o vetor bônus para que ele possa ser somado à matriz
# Mas forma de `bonus_por_produto` (3,) é incompatível com (3, 4)
# Para somar, precisamos que tenha a forma (3, 1) para o broadcast funcionar nas colunas
bonus_formatado = bonus_por_produto.reshape(3, 1)

In [47]:
bonus_formatado.shape

(3, 1)

In [48]:
print("\nBônus por Produto:\n")
print(bonus_formatado)


Bônus por Produto:

[[ 5]
 [10]
 [15]]


In [49]:
# Agora sim
faturamento_com_bonus = faturamento + bonus_formatado
print("\nFaturamento com Bônus (via Broadcasting):\n")
print(faturamento_com_bonus)


Faturamento com Bônus (via Broadcasting):

[[105 115 125 135]
 [210 220 230 240]
 [315 325 335 345]]


## 8. Manipulação de Formato de Arrays
<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
Muitas vezes precisamos reorganizar os dados em um formato diferente para análise ou para alimentar um modelo de IA.

In [50]:
# Criando um array 1D com 12 elementos
dados_sequenciais = np.arange(12)
print(f"\nArray original (1D): {dados_sequenciais}\n")


Array original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]



In [51]:
# Remodelando para uma matriz 3x4
matriz_3x4 = dados_sequenciais.reshape(3, 4)
print(f"\nMatriz 3x4:\n{matriz_3x4}\n")


Matriz 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [52]:
# Transpondo a matriz (trocando linhas por colunas)
matriz_transposta = matriz_3x4.T
print(f"\nMatriz Transposta (4x3):\n{matriz_transposta}\n")


Matriz Transposta (4x3):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



In [53]:
# Achatando a matriz de volta para um array 1D
array_achatado = matriz_transposta.flatten()
print(f"\nArray achatado (1D): {array_achatado}")


Array achatado (1D): [ 0  4  8  1  5  9  2  6 10  3  7 11]


<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
## 9. Operações Matemáticas com Matrizes

In [ ]:
# Criando duas matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
print(f"\nMatriz A:\n{A}\n")
print(f"Matriz B:\n{B}\n")

In [ ]:
# Produto de Matrizes (diferente da multiplicação elemento a elemento)
# Usando o operador @
produto_matricial = A @ B
print(f"\nProduto de A por B:\n\n{produto_matricial}\n")

Nesse trecho acima, são criadas duas matrizes 2×2 chamadas A e B. Em seguida, é realizado o produto matricial entre elas usando o operador @. Diferente da multiplicação elemento a elemento (que faz a operação posição por posição), o produto matricial segue as regras da álgebra linear: cada elemento da matriz resultante é obtido multiplicando os elementos de uma linha da primeira matriz pelos elementos de uma coluna da segunda e somando esses produtos. O cálculo do produto é:

[ [1 * 5 + 2 * 7, 1 * 6 + 2 * 8], [3 * 5 + 4 * 7, 3 * 6 + 4 * 8] ] = [[19, 22], [43, 50]]

In [ ]:
# Usando np.dot() ao invés de @
produto_matricial = np.dot(A, B)
print(f"Produto de A por B:\n{produto_matricial}\n")

**ATENÇÃO**: Quando fazemos:

produto_matricial = A @ B

ou

produto_matricial = np.dot(A, B)


Estamos realizando o produto matricial clássico da Álgebra Linear. Cada elemento do resultado é a soma dos produtos entre as linhas de A e as colunas de B.

In [ ]:
print(f"\nMatriz A:\n{A}\n")
print(f"Matriz B:\n{B}\n")

In [ ]:
# Element wise
produto_element_wise = A * B
print(f"Multiplicação Element-wise de A por B:\n{produto_element_wise}\n")

**ATENÇÃO**: Quando fazemos:

produto_elementwise = A * B


O NumPy multiplica cada elemento na mesma posição das duas matrizes. Não há soma de produtos; é apenas posição a posição. 

---

Normalmente usamos o produto matricial (@ ou np.dot) quando implementamos modelos de Machine Learning ou IA com redes neurais, e não a multiplicação elemento a elemento. Motivo:

Cada camada de uma rede neural realiza uma transformação linear dos dados de entrada. Essa transformação é feita multiplicando a matriz de pesos da camada (W) pelo vetor ou matriz de entradas (X):

saída = X @ W + bias


- X → entradas (amostras × features)

- W → pesos (features × neurônios)

- bias → deslocamento adicionado depois

O resultado é uma nova matriz onde cada neurônio combina as entradas por meio de somas ponderadas.
<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->
Esse processo só é possível com o produto matricial, porque ele combina cada entrada com todos os pesos de cada neurônio ao mesmo tempo, gerando uma saída que depois passa por uma função de ativação (ReLU, sigmoid, etc.).

A multiplicação element-wise (*) é usada em redes neurais, mas em casos específicos, como:

- Hadamard product em algumas arquiteturas (por exemplo, em gates de LSTM/GRU ou atenção em Transformers);

- Aplicar máscaras ou pesos individuais diretamente em cada elemento.

Mas a operação central de treino e propagação em redes neurais é sempre o produto matricial, porque ela permite aprender pesos que combinam múltiplas entradas para gerar representações mais complexas.

**Aqui vai um segredo (não conte para ninguém): Todo modelo de IA é, de fato, um conjunto de operações com matrizes. :-)**

Mais algumas operações com matrizes NumPy.

In [ ]:
# Criando duas matrizes 2x2

A = np.array([[10, 20],
              [30, 40]])

B = np.array([[7, 14],
              [4, 3]])

In [ ]:
# Soma de matrizes
soma = A + B

In [ ]:
# Subtração de matrizes
subtracao = A - B

In [ ]:
# Divisão elemento a elemento
divisao = A / B

In [ ]:
print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
print("\nSoma A + B:\n", soma)
print("\nSubtração A - B:\n", subtracao)
print("\nDivisão A / B:\n", divisao)

## 10. Exemplo de Operações com Matrizes no Processamento de Imagens
<!-- Trabalho Desenvolvido no Curso da Data Science Academy - www.datascienceacademy.com.br -->

![DSA](imagem2.png)

https://blog.dsacademy.com.br/trilha-de-aprendizagem-da-formacao-analista-de-dados/

In [ ]:
from PIL import Image
import numpy as np

# Abre a imagem
img = Image.open("imagem2.png")

# Converte para array NumPy
array_img = np.array(img)

print("\nFormato do array:\n", array_img.shape)  
# (altura, largura, 3) → 3 canais = R, G, B

# Obtendo as dimensões
altura, largura, canais = array_img.shape
print(f"\nAltura: {altura}, Largura: {largura}, Canais: {canais}")

# Separando cada canal
R = array_img[:, :, 0]  # Canal vermelho
G = array_img[:, :, 1]  # Canal verde
B = array_img[:, :, 2]  # Canal azul

# Extraindo um dos pixels
print("\nExtraindo um dos pixels:\n", array_img[590, 1287])  

# Pixel específico (ex: linha 590, coluna 1287)
pixel = array_img[590, 1287]
r, g, b = pixel
print(f"\nPixel [617,1287] → R={r}, G={g}, B={b}")

---

Vamos agora recortar um pedaço da imagem:

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# --- Carrega a imagem ---
img = Image.open("imagem2.png")
array_img = np.array(img)

# Obtendo dimensões
altura, largura, canais = array_img.shape
print(f"Altura: {altura}, Largura: {largura}, Canais: {canais}")

# --- Definindo um corte central ---
# Tamanho do recorte 
recorte_h = 280
recorte_w = 400

# Definimos o centro da matriz
centro_y = altura // 2
centro_x = largura // 2

# Calculando limites para o recorte central (operações com matrizes para fatiar a imagem)
y_inicio = centro_y - recorte_h // 2
y_fim = centro_y + recorte_h // 2
x_inicio = centro_x - recorte_w // 2
x_fim = centro_x + recorte_w // 2

# Fazendo o slice (fatiamento) no array
corte_central = array_img[y_inicio:y_fim, x_inicio:x_fim]

print(f"\nFormato do recorte: {corte_central.shape}")  

# --- Mostra a imagem original e o corte ---
plt.figure(figsize = (10,5))
plt.subplot(1,2,1)
plt.title("Imagem Original")
plt.imshow(array_img)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Corte Central")
plt.imshow(corte_central)
plt.axis("off")

plt.show()

Este jupyter apenas arranha a superfície do NumPy trazendo os fundamentos essenciais. Há muito mais a explorar com o NumPy, o que você encontra em diversos cursos aqui na DSA.

# Fim

Este curso é inteiramente gratuito e com certificado de conclusão. Se estiver gostando, ajude o trabalho da Data Science Academy e compartilhe nas suas redes. Conte para as pessoas o que estamos fazendo aqui, oferecendo material de alto nível de forma gratuita. Este é o link da página do curso:

https://www.datascienceacademy.com.br/course/fundamentos-de-linguagem-python-do-basico-a-aplicacoes-de-ia